### ISSUE TITLE
Requested API level 31 is larger than maximum we have, returning API level 28 instead.

### ISSUE THREAD

**Issue by julianfairfax** [Efreak/seeker-fdroid#2]
This is concerning self-hosting this repo, not this repo in and of itself. When you have apps that have a high API level, such as 31, this is displayed in the log: `Requested API level 31 is larger than maximum we have, returning API level 28 instead.`. Is there some way of fixing this issue so that the correct API level is used?

**Comment by Efreak** [comment]
I saw that too. I have no idea what it means, but the repo still works fine in fdroid (see the logs in the action tab). For more information, you'd have to contact the f-droid team, as this uses the official fdroid PPA.

Now that there's an official repo at jackBonadies/SeekerAndroid (in the [fdroid branch](https://github.com/jackBonadies/SeekerAndroid)), I'll be archiving this repo on next release; if you have issues after that, direct them to [efreak/fdroid-action](https://github.com/efreak/fdroid-action) or [xarantolus/fdroid](https://github.com/xarantolus/fdroid).
