### ISSUE TITLE
Host apps on GitLab

### ISSUE THREAD

**Issue by julianfairfax** [Efreak/seeker-fdroid#4]
Sorry to bother you for the forth time, but I'm trying to host my repo on GitLab now, and it seems there is one small problem: metascoop appears to only download releases from GitHub (https://github.com/Efreak/seeker-fdroid/blob/main/metascoop/main.go#L82-L101, https://github.com/Efreak/seeker-fdroid/blob/main/metascoop/main.go#L157-L162, https://github.com/Efreak/seeker-fdroid/blob/main/metascoop/apps/info.go#L15-L27, and https://github.com/Efreak/seeker-fdroid/blob/main/metascoop/apps/info.go#L55-L73).

This is fine for apps on GitHub, but as I'm hosting apps on GitLab (which I can set with the git url), it's not working. Do you happen to know if there's any way I can change this without rewriting the whole code? Thanks for your help!

**Comment by Efreak** [comment]
That's correct, metascoop uses the GitHub releases API. I don't actually know much about this, as I didn't write it; you're better off asking @xarantolus in [xarantolus/fdroid](https://github.com/xarantolus/fdroid).

**Comment by Efreak** [comment]
I'm not actually sure how metascoop works, I've only personally looked into it enough to change the number of releases it downloads (the original downloads all releases ever), but if it grabs the metadata properly, you may be able to just use that portion and get the binaries with [`glab`](https://glab.readthedocs.io/en/latest/release/download.html)

**Comment by julianfairfax** [comment]
> I'm not actually sure how metascoop works, I've only personally looked into it enough to change the number of releases it downloads (the original downloads all releases ever), but if it grabs the metadata properly, you may be able to just use that portion and get the binaries with [`glab`](https://glab.readthedocs.io/en/latest/release/download.html)

Well it grabs the metadata from GitHub also. It's written in go so I have little idea of how change any of it. Maybe I can mention @xarantolus here instead of creating a whole new issue

**Comment by xarantolus** [comment]
As you have already noticed, the problem is that the program is very much integrated with GitHubs' API etc (and the code in general is a mess, as it was more a "can this work?" type of project and not a very well planned one. There's a lot of stuff missing, but with the current code it's not really a good idea to add more. Also I don't have the time).

However, adding GitLab support should be possible, you would have to replace the API calls to GitHub. The currently hackiest but easiest way to do that would be in main.go before the `githubClient.Repositories.Get` call (basically add a differentiation betwenn gitlab/github); you would probably also need a way to provide an access token via a flag and then change the release list & asset download as well. It should be possible to do without much experience in Go

**Comment by julianfairfax** [comment]
> It should be possible to do without much experience in Go

I'm not so sure about that.

What does the code itself actually do? Fetch the latest release? Download it? Then what? How is the F-Droid-compatible repo generated? I think it would probably be easier for me just to write something new in bash than trying to learn enough go to modify this a bit.

**Comment by julianfairfax** [comment]
> > It should be possible to do without much experience in Go
> 
> I'm not so sure about that.
> 
> What does the code itself actually do? Fetch the latest release? Download it? Then what? How is the F-Droid-compatible repo generated? I think it would probably be easier for me just to write something new in bash than trying to learn enough go to modify this a bit.

That is what I have done. Check out https://gitlab.com/julianfairfax/fdroid-repo/-/blob/main/update.sh if you're interested.

**Comment by julianfairfax** [comment]
I'm not using this code anymore, and I also won't be subscribing to this issue again (mention me if you need me), but I am dropping by to say that my repo is now entirely compatible with GitHub Pages as a hosting provider too: https://gitlab.com/julianfairfax/fdroid-repo.

Previously it was made with only GitLab in mind, but it can now do both.
